name: Docker build
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - .devcontainer
      - .github/workflows/buildx-latest.yml
      - .github/workflows/buildx-release.yml
      - .github/workflows/dockerhub-description.yml
      - .github/workflows/labels.yml
      - .vscode
      - docker-compose.yml
      - LICENSE
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Buildx
        run: |
          docker buildx build  \
            --progress plain \
            --platform=linux/amd64 \
            .
