name: Docker build
on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/buildx-pr.yml
      - shell/**
      - .dockerignore
      - Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Buildx
        run: |
          docker buildx build  \
            --progress plain \
            --platform=linux/amd64 \
            .
